"""Add conta_id to MovimentacaoInvestimento

Revision ID: 19fec139b4e2
Revises: 6266f854df14
Create Date: 2025-08-18 15:24:50.498569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fec139b4e2'
down_revision = '6266f854df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_investimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_movimentacao_conta', 'conta', ['conta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_investimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacao_conta', type_='foreignkey')
        batch_op.drop_column('conta_id')

    # ### end Alembic commands ###
