"""Add discount field to Transaction model

Revision ID: 30396cde7039
Revises: a855cb3cb47e
Create Date: 2025-05-22 06:38:27.980705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30396cde7039'
down_revision = 'a855cb3cb47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
