"""Nova migração

Revision ID: 3cc49f42dc41
Revises: 
Create Date: 2025-04-10 15:30:43.730779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc49f42dc41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_categories')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    op.create_table('_alembic_tmp_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('exclusive', sa.BOOLEAN(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
