"""add_conta_id_to_movimentacao_investimento_simple

Revision ID: 577462efa927
Revises: 19fec139b4e2
Create Date: 2025-08-30 10:10:35.644824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577462efa927'
down_revision = '19fec139b4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_conta')
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # Adicionar coluna conta_id como nullable
    with op.batch_alter_table('movimentacao_investimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_investimento', schema=None) as batch_op:
        batch_op.alter_column('conta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_conta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_id', sa.INTEGER(), nullable=False),
    sa.Column('saldo', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('saldo_atual', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_conta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
