"""remove relacionamento conta de Investimento

Revision ID: 6266f854df14
Revises: 
Create Date: 2025-08-17 18:31:05.131866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6266f854df14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Remover apenas as colunas de investimento
    with op.batch_alter_table('investimento', schema=None) as batch_op:
        batch_op.drop_column('conta_id')
        batch_op.drop_column('saldo_investimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_investimento', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('conta_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_investimento_conta', 'conta', ['conta_id'], ['id'])

    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
