"""Recriando migrações

Revision ID: 7cd5ffdbfed3
Revises: d6159fe029d1
Create Date: 2025-03-27 06:44:24.858333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd5ffdbfed3'
down_revision = 'd6159fe029d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_categories')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('exclusive', sa.VARCHAR(length=20), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
