"""Add due_date field to Transaction model

Revision ID: a855cb3cb47e
Revises: 3cc49f42dc41
Create Date: 2025-05-22 06:29:24.846785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a855cb3cb47e'
down_revision = '3cc49f42dc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
