"""Descrição da mudança no modelo

Revision ID: d6159fe029d1
Revises: 
Create Date: 2025-03-25 13:52:37.939108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6159fe029d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('exclusive',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('exclusive',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('exclusive',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('exclusive',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
